# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\NguyenCuong\S4-190\qt_S4190_v1.1\design.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 250)
        MainWindow.setMinimumSize(QtCore.QSize(450, 250))
        MainWindow.setMaximumSize(QtCore.QSize(450, 250))
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        icon = QtGui.QIcon.fromTheme("/Logo.png")
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setMinimumSize(QtCore.QSize(450, 250))
        self.centralwidget.setMaximumSize(QtCore.QSize(450, 250))
        self.centralwidget.setStyleSheet("background-color: #f1f1f1")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.MainWrapper = QtWidgets.QGroupBox(self.centralwidget)
        self.MainWrapper.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.MainWrapper.setStyleSheet("background-color: #c7c7c7; border: 1px solid #fff;")
        self.MainWrapper.setTitle("")
        self.MainWrapper.setObjectName("MainWrapper")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.MainWrapper)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ResultBox = QtWidgets.QGroupBox(self.MainWrapper)
        self.ResultBox.setStyleSheet("background-color: rgb(85, 85, 85); border-radius: 4px; color: #fff;font-weight: bold;")
        self.ResultBox.setTitle("")
        self.ResultBox.setObjectName("ResultBox")
        self.ResultText = QtWidgets.QLabel(self.ResultBox)
        self.ResultText.setGeometry(QtCore.QRect(30, 0, 140, 51))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.ResultText.setFont(font)
        self.ResultText.setStyleSheet("\n"
"font: 12pt \"Segoe UI\"; border: none; color: #fff; background: none; font-weight: bold;")
        self.ResultText.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultText.setObjectName("ResultText")
        self.ResultContent = QtWidgets.QLabel(self.ResultBox)
        self.ResultContent.setGeometry(QtCore.QRect(2, 41, 199, 171))
        self.ResultContent.setStyleSheet("font-size: 16px;\n"
"font: 16pt \"Segoe UI\"; border: 1px solid #ccc; color: #999; background-color: #fff;")
        self.ResultContent.setAlignment(QtCore.Qt.AlignCenter)
        self.ResultContent.setObjectName("ResultContent")
        self.horizontalLayout_2.addWidget(self.ResultBox)
        self.CamBox1 = QtWidgets.QGroupBox(self.MainWrapper)
        self.CamBox1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CamBox1.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255)); border-radius: 4px; color: #fff; font-weight: bold; color: #fff;")
        self.CamBox1.setObjectName("CamBox1")
        self.Frame1 = QtWidgets.QLabel(self.CamBox1)
        self.Frame1.setGeometry(QtCore.QRect(0, 0, 203, 212))
        self.Frame1.setStyleSheet("border-radius: 4px;")
        self.Frame1.setText("")
        self.Frame1.setObjectName("Frame1")
        self.horizontalLayout_2.addWidget(self.CamBox1)
        self.horizontalLayout.addWidget(self.MainWrapper)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Scanner S4-190"))
        self.ResultText.setText(_translate("MainWindow", "RESULT:"))
        self.ResultContent.setText(_translate("MainWindow", "NONE"))
        self.CamBox1.setTitle(_translate("MainWindow", "CAMERA 1"))
